WITH
  sessions AS (
  SELECT
    TIMESTAMP_SECONDS(visitStartTime) AS session_ts,
    CONCAT(fullVisitorId, CAST(visitId AS string)) AS visitor_session_id,
    visitId AS session_id,
    fullVisitorId AS full_visitor_id,
    visitNumber AS visit_number,
    clientId AS client_id,
    userId AS user_id,
    channelGrouping AS channel_grouping,
    socialEngagementType AS social_engagement_type,
    device.browser AS device_browser,
    device.browserVersion AS device_browser_version,
    device.browserSize device_browser_size,
    device.operatingSystem deviceoperating_system,
    device.operatingSystemVersion deviceoperatingSystemVersion,
    device.isMobile AS deviceis_mobile,
    device.mobileDeviceBranding AS devicemobile_device_branding,
    device.mobileDeviceModel AS device_mobile_device_model,
    device.mobileInputSelector AS device_mobile_input_selector,
    device.mobileDeviceInfo AS device_mobile_device_info,
    device.mobileDeviceMarketingName AS device_mobile_device_marketing_name,
    device.flashVersion AS device_flashVersion,
    device.javaEnabled AS device_javaEnabled,
    device.LANGUAGE AS device_language,
    device.screenColors AS device_browserscreen_colors,
    device.screenResolution AS device_screen_resolution,
    geoNetwork.networkDomain AS device_network_domain,
    geoNetwork.latitude AS geo_network_latitude,
    geoNetwork.longitude AS geo_network_longitude,
    geoNetwork.networkLocation AS geo_network_network_location,
    geoNetwork.cityId AS geo_network_city_id,
    geoNetwork.city AS geo_network_city,
    geoNetwork.metro AS geo_network_metro,
    geoNetwork.region AS geo_network_region,
    geoNetwork.country AS geo_network_country,
    geoNetwork.subContinent AS geo_network_sub_continent,
    geoNetwork.continent AS geo_network_continent,
    totals.visits AS total_session_visits,
    totals.hits AS total_session_hits,
    totals.pageviews AS total_session_pageviews,
    totals.timeOnSite AS total_session_time_on_site,
    totals.bounces AS total_session_bounces,
    totals.transactions AS total_session_transactions,
    totals.transactionRevenue AS total_session_transaction_revenue,
    totals.newVisits AS session_new_visits,
    totals.screenviews AS session_screenviews,
    totals.uniqueScreenviews AS session_unique_screenviews,
    totals.timeOnScreen AS session_time_on_screen,
    totals.totalTransactionRevenue AS session_total_transaction_revenue,
    totals.sessionQualityDim AS session_quality_dim,
    trafficSource.referralPath AS traffic_source_referral_path,
    trafficSource.campaign AS traffic_source_campaign,
    trafficSource.source AS traffic_source_source,
    trafficSource.medium AS traffic_source_medium,
    trafficSource.keyword AS traffic_source_keyword,
    trafficSource.adContent AS traffic_source_ad_content,
    MAX(IF(customDimensions.index=1,customDimensions.value,NULL)) WITHIN RECORD AS session_custom_dimension_1,
    MAX(IF(customDimensions.index=2,customDimensions.value,NULL)) WITHIN RECORD AS session_custom_dimension_2
  FROM
    {{ ref('google_analytics_sample')}}
   )
SELECT
  *,
  LAG(session_ts,1) OVER (PARTITION BY full_visitor_id ORDER BY session_ts) previous_session_ts,
  TIMESTAMP_DIFF(session_ts,LAG(session_ts,1) OVER (PARTITION BY full_visitor_id ORDER BY session_ts),MINUTE) mins_since_previous_visitor_session
FROM
  sessions
